### ISSUE TITLE
Video freezes but does not crash until the user switches channels or DMs, pauses/unpauses the video, or minimizes Discord.

### ISSUE THREAD

**Issue by monsieurbaguette** [emlin2019/YUVCrasher#3]
Essentially, upon playing the output video in Discord, the video freezes up at the intended crash point, but Discord itself does not freeze/hang or crash until some form of user input (besides things that don't involve switching channels/windows or interacting with the video after the freeze point) is given. I have hardware acceleration on, and I am currently on Windows 10. I have also seen other videos that work properly, so I don't think it has to do with my hardware or settings.

(As a side note, other users that I've shared the video with are experiencing the same issue.)

**Comment by emlin2019** [comment]
Imma close this issue, since I cannot controll anything about the crashing itself.
