### ISSUE TITLE
Crash not caused

### ISSUE THREAD

**Issue by nilPadisha** [emlin2019/YUVCrasher#5]
I've tried both releases, the video I've used is an mp4 file that's 10 seconds long.
It turns it into a file that looks like it's 800 minutes and the video stops after the 10 seconds, but no crash is caused like the other videos do.

**Comment by nilPadisha** [comment]
The output file:
https://user-images.githubusercontent.com/30347112/104222154-2cbb9e00-5442-11eb-85cd-39e300bf27d9.mp4

The file I'm trying to mimic.
https://user-images.githubusercontent.com/30347112/104222172-334a1580-5442-11eb-8d6b-0be29b239f04.mp4

**Comment by Down200** [comment]
Ever find a fix for this? I'm finding a similar issue.
