### ISSUE TITLE
error while creating the video

### ISSUE THREAD

**Issue by zehedev** [emlin2019/YUVCrasher#6]
command I have used:
`D:\clips>D:\clips\yuvcrasher\YUVCrasher.exe videoiwanttocrash.mp4`

error:
```
[concat @ 0000027ba997de40] Impossible to open 'sample.bin'
join.txt: No such file or directory
```

how does the directory look like:

![image](https://user-images.githubusercontent.com/61054475/114317521-11445a00-9b3b-11eb-943d-fd8a39f36817.png)

I am still getting output.mp4 but it won't cause discord to crash

**Comment by emlin2019** [comment]
ffmpeg issue. Closed

**Comment by Mixarar** [comment]
> command I have used:
> `D:\clips>D:\clips\yuvcrasher\YUVCrasher.exe videoiwanttocrash.mp4`
> 
> error:
> 
> ```
> [concat @ 0000027ba997de40] Impossible to open 'sample.bin'
> join.txt: No such file or directory
> ```
> 
> how does the directory look like:
> 
> ![image](https://user-images.githubusercontent.com/61054475/114317521-11445a00-9b3b-11eb-943d-fd8a39f36817.png)
> 
> I am still getting output.mp4 but it won't cause discord to crash

no such file is because you need to CD into that directory and then run the comand. But it doesnt crash, it stopped working
